- name: setup mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql server
    ansible.mysql.package:
      name: mysql
      state: present

  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes
      
  - name: setup root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1